# export_blender.jl
#
# Export IGA geometry (NURBS patches, control points, control net) to OBJ/PLY
# files for Blender rendering.  Companion Blender Python script is generated
# by `write_blender_script()`.
#
# Usage (from pressurized_sphere_deltoidal.jl or any solver):
#
#   include("export_blender.jl")
#   export_blender("sphere", npc, nsd, npd, p_mat, n_mat, KV, P, B;
#                   U=U, ID=ID, E=E, nu=nu, n_vis=6,
#                   scalar_fn=my_stress_fn, scalar_name="von_mises")
#
# This creates:
#   sphere_patch_1.obj ... sphere_patch_N.obj   (tessellated NURBS surfaces)
#   sphere_cpnet_1.obj ... sphere_cpnet_N.obj   (control net as wireframe)
#   sphere_cpts.obj                              (control points as vertices)
#   sphere_import.py                             (Blender Python import script)

import Pkg; Pkg.activate(joinpath(@__DIR__, ".."))
using IGAros
using LinearAlgebra, Printf

# ─── Re-use _kv_sample if not already defined ────────────────────────────────
if !@isdefined(_kv_sample)
    function _kv_sample(kv_vec::AbstractVector{Float64}, n_per_span::Int)::Vector{Float64}
        breaks = unique(kv_vec)
        pts = Float64[]
        for i in 1:length(breaks)-1
            append!(pts, range(breaks[i], breaks[i+1]; length = n_per_span + 1)[1:end-1])
        end
        push!(pts, breaks[end])
        return pts
    end
end

# ─── Coolwarm colormap (blue → white → red) ─────────────────────────────────

"""
    _turbo(t) -> (r, g, b)

Turbo colormap (Google/Mikhailov 2019): dark blue → cyan → green → yellow → red.
Attempt to approximate the sRGB Turbo LUT with piecewise-linear interpolation
through 8 key stops.
"""
function _turbo(t::Float64)::Tuple{Float64, Float64, Float64}
    t = clamp(t, 0.0, 1.0)
    # Key stops: (t, r, g, b)
    stops = [
        (0.00, 0.18995, 0.07176, 0.23217),
        (0.14, 0.15284, 0.30723, 0.72549),
        (0.28, 0.09267, 0.58413, 0.90924),
        (0.42, 0.19659, 0.83490, 0.69107),
        (0.56, 0.51940, 0.96479, 0.35816),
        (0.70, 0.84000, 0.93230, 0.11680),
        (0.84, 0.98468, 0.68513, 0.07920),
        (1.00, 0.70567, 0.01555, 0.15023),
    ]
    # Find interval
    for i in 1:length(stops)-1
        t0, r0, g0, b0 = stops[i]
        t1, r1, g1, b1 = stops[i+1]
        if t <= t1 || i == length(stops)-1
            s = (t - t0) / (t1 - t0)
            return (r0 + s*(r1-r0), g0 + s*(g1-g0), b0 + s*(b1-b0))
        end
    end
    return stops[end][2:4]
end

# ─── OBJ writer for a single triangulated surface patch ──────────────────────

"""
    write_patch_obj(fname, pts, tris; normals=nothing, scalars=nothing)

Write a triangulated surface to Wavefront OBJ.

- `pts`:     (3, n_pts) — vertex positions
- `tris`:    (3, n_tri) — 1-based triangle connectivity
- `normals`: (3, n_pts) — optional vertex normals
- `scalars`: (n_pts,)   — optional per-vertex scalar (written as vertex color r=val, g=val, b=val)
"""
function write_patch_obj(
    fname::String,
    pts::Matrix{Float64},
    tris::Matrix{Int};
    normals::Union{Nothing, Matrix{Float64}} = nothing,
    scalars::Union{Nothing, Vector{Float64}} = nothing
)
    n_pts = size(pts, 2)
    open(fname, "w") do f
        println(f, "# IGA patch surface — generated by export_blender.jl")
        println(f, "# Vertices: $n_pts, Triangles: $(size(tris, 2))")
        println(f)

        if !isnothing(scalars)
            # Normalize scalar to [0,1] and map through coolwarm colormap
            smin, smax = extrema(scalars)
            if smax > smin
                s01 = (scalars .- smin) ./ (smax - smin)
            else
                s01 = fill(0.5, n_pts)
            end
            for i in 1:n_pts
                r, g, b = _turbo(s01[i])
                @printf(f, "v %.8e %.8e %.8e %.6f %.6f %.6f\n",
                        pts[1,i], pts[2,i], pts[3,i], r, g, b)
            end
            println(f, "# scalar_range $smin $smax")
        else
            for i in 1:n_pts
                @printf(f, "v %.8e %.8e %.8e\n", pts[1,i], pts[2,i], pts[3,i])
            end
        end

        if !isnothing(normals)
            println(f)
            for i in 1:n_pts
                @printf(f, "vn %.8e %.8e %.8e\n", normals[1,i], normals[2,i], normals[3,i])
            end
            println(f)
            for j in 1:size(tris, 2)
                @printf(f, "f %d//%d %d//%d %d//%d\n",
                        tris[1,j], tris[1,j], tris[2,j], tris[2,j], tris[3,j], tris[3,j])
            end
        else
            println(f)
            for j in 1:size(tris, 2)
                @printf(f, "f %d %d %d\n", tris[1,j], tris[2,j], tris[3,j])
            end
        end
    end
    @printf("  Wrote %s  (%d vertices, %d triangles)\n", fname, n_pts, size(tris, 2))
end

# ─── OBJ writer for control net (edges) ─────────────────────────────────────

"""
    write_cpnet_obj(fname, B, P, n_mat_pc)

Write control net as an OBJ file with line (`l`) elements.
ParaView and Blender both render these as wireframe.

- `B`:        global CP array (ncp × 4)
- `P`:        local-to-global CP indices for this patch
- `n_mat_pc`: [n1, n2] or [n1, n2, n3] — CPs per direction
"""
function write_cpnet_obj(
    fname::String,
    B::Matrix{Float64},
    Ppc::Vector{Int},
    n_mat_pc::Vector{Int}
)
    npd = length(n_mat_pc)
    n_cp = length(Ppc)

    open(fname, "w") do f
        println(f, "# IGA control net — generated by export_blender.jl")
        println(f, "# Control points: $n_cp")
        println(f)

        # Vertices
        for i in 1:n_cp
            A = Ppc[i]
            @printf(f, "v %.8e %.8e %.8e\n", B[A,1], B[A,2], B[A,3])
        end

        println(f)

        if npd == 2
            n1, n2 = n_mat_pc
            # Lines along ξ (rows of the CP grid)
            for j in 1:n2
                for i in 1:n1-1
                    a = (j-1)*n1 + i
                    b = a + 1
                    println(f, "l $a $b")
                end
            end
            # Lines along η (columns of the CP grid)
            for i in 1:n1
                for j in 1:n2-1
                    a = (j-1)*n1 + i
                    b = a + n1
                    println(f, "l $a $b")
                end
            end

        elseif npd == 3
            n1, n2, n3 = n_mat_pc
            # Lines along ξ
            for k in 1:n3, j in 1:n2
                for i in 1:n1-1
                    a = (k-1)*n1*n2 + (j-1)*n1 + i
                    println(f, "l $a $(a+1)")
                end
            end
            # Lines along η
            for k in 1:n3, i in 1:n1
                for j in 1:n2-1
                    a = (k-1)*n1*n2 + (j-1)*n1 + i
                    b = a + n1
                    println(f, "l $a $b")
                end
            end
            # Lines along ζ
            for j in 1:n2, i in 1:n1
                for k in 1:n3-1
                    a = (k-1)*n1*n2 + (j-1)*n1 + i
                    b = a + n1*n2
                    println(f, "l $a $b")
                end
            end
        end
    end
    @printf("  Wrote %s  (%d control points)\n", fname, n_cp)
end

# ─── Tessellate a 3D NURBS patch outer surface for Blender ───────────────────

"""
    tessellate_patch_surface(pc, face, nsd, npd, p_mat, n_mat, KV, P, B;
                             n_vis=6, U=nothing, ID=nothing,
                             E=nothing, nu=nothing)

Evaluate a NURBS patch face on a regular (n_vis × n_vis) per-element grid
and return triangulated surface data.

- `face`: which parametric face to tessellate (1..6 for 3D, 0 for 2D=full patch)
- Returns `(pts, tris, normals, scalars_dict)`.
"""
function tessellate_patch_surface(
    pc::Int, face::Int,
    nsd::Int, npd::Int,
    p_mat::Matrix{Int}, n_mat::Matrix{Int},
    KV, P::Vector{Vector{Int}}, B::Matrix{Float64};
    n_vis::Int = 6,
    U::Union{Nothing, Vector{Float64}} = nothing,
    ID::Union{Nothing, Matrix{Int}} = nothing,
    E::Union{Nothing, Float64} = nothing,
    nu::Union{Nothing, Float64} = nothing,
    scalar_fn::Union{Nothing, Function} = nothing,
    deformed::Bool = false
)
    pv  = p_mat[pc, :]
    nv  = n_mat[pc, :]
    kv  = KV[pc]
    Ppc = P[pc]

    # Determine which two parametric directions span the face
    if npd == 2
        # Full 2D patch
        s1 = _kv_sample(collect(kv[1]), n_vis)
        s2 = _kv_sample(collect(kv[2]), n_vis)
        dir_a, dir_b = 1, 2
        fixed_dir, fixed_val = 0, 0.0
    elseif npd == 3
        # 3D: extract one face
        # Face convention: 1=ζ_min, 6=ζ_max, 2=ξ_max, 4=ξ_min, 3=η_max, 5=η_min
        if face == 1      # ζ = min
            dir_a, dir_b = 1, 2; fixed_dir = 3; fixed_val = collect(kv[3])[pv[3]+1]
        elseif face == 6  # ζ = max
            dir_a, dir_b = 1, 2; fixed_dir = 3; fixed_val = collect(kv[3])[nv[3]+1]
        elseif face == 4  # ξ = min
            dir_a, dir_b = 2, 3; fixed_dir = 1; fixed_val = collect(kv[1])[pv[1]+1]
        elseif face == 2  # ξ = max
            dir_a, dir_b = 2, 3; fixed_dir = 1; fixed_val = collect(kv[1])[nv[1]+1]
        elseif face == 5  # η = min
            dir_a, dir_b = 1, 3; fixed_dir = 2; fixed_val = collect(kv[2])[pv[2]+1]
        elseif face == 3  # η = max
            dir_a, dir_b = 1, 3; fixed_dir = 2; fixed_val = collect(kv[2])[nv[2]+1]
        else
            error("Invalid face: $face")
        end
        s1 = _kv_sample(collect(kv[dir_a]), n_vis)
        s2 = _kv_sample(collect(kv[dir_b]), n_vis)
    end

    # For 3D faces: extract the 2D face CP indices once
    local Pface, ps_face, ns_face, kv_face
    if npd == 3
        ps_face = [pv[dir_a], pv[dir_b]]
        ns_face = [nv[dir_a], nv[dir_b]]
        kv_face = [collect(kv[dir_a]), collect(kv[dir_b])]
        Pface = _extract_face_cps(Ppc, nv, fixed_dir, fixed_val, kv, pv)
    end

    nd1, nd2 = length(s1), length(s2)
    n_pts = nd1 * nd2
    pts     = zeros(3, n_pts)
    normals = zeros(3, n_pts)
    svm     = zeros(n_pts)

    idx = 0
    for (j, xi_b) in enumerate(s2), (i, xi_a) in enumerate(s1)
        idx += 1

        if npd == 2
            ps2 = [pv[1], pv[2]]
            ns2 = [nv[1], nv[2]]
            kv2 = [collect(kv[1]), collect(kv[2])]
            x, dxd1, dxd2, _, _ = eval_surface_point(xi_a, xi_b, ps2, ns2, kv2, B, Ppc, nsd)
        else
            x, dxd1, dxd2, _, _ = eval_surface_point(xi_a, xi_b, ps_face, ns_face, kv_face, B, Pface, nsd)
        end

        nn = cross(dxd1, dxd2); nn_norm = norm(nn)
        nn = nn_norm > 1e-14 ? nn / nn_norm : [0.0, 0.0, 1.0]

        pts[1:nsd, idx] = x
        normals[1:nsd, idx] = nn

        if !isnothing(scalar_fn)
            svm[idx] = scalar_fn(x...)
        end
    end

    # Triangulate the structured grid
    n_tri = 2 * (nd1 - 1) * (nd2 - 1)
    tris = zeros(Int, 3, n_tri)
    t = 0
    for j in 1:nd2-1, i in 1:nd1-1
        a = (j-1)*nd1 + i
        b = a + 1
        c = a + nd1
        d = c + 1
        t += 1; tris[:, t] = [a, b, d]
        t += 1; tris[:, t] = [a, d, c]
    end

    return pts, tris, normals, svm
end

# ─── Extract face CPs from a 3D patch ───────────────────────────────────────

"""
    _extract_face_cps(Ppc, nv, fixed_dir, fixed_val, kv, pv) -> Vector{Int}

Extract the control point indices for one face of a 3D NURBS patch.
The face is defined by `fixed_dir` (1=ξ, 2=η, 3=ζ) at its min or max value.
Returns CPs in (dir_a-inner, dir_b-outer) ordering for `eval_surface_point`.
"""
function _extract_face_cps(
    Ppc::Vector{Int},
    nv::AbstractVector{Int},
    fixed_dir::Int,
    fixed_val::Float64,
    kv, pv::AbstractVector{Int}
)
    n1, n2, n3 = nv[1], nv[2], nv[3]
    kv_d = collect(kv[fixed_dir])

    # Determine if fixed_val is min or max
    val_min = kv_d[pv[fixed_dir] + 1]
    val_max = kv_d[nv[fixed_dir] + 1]
    if abs(fixed_val - val_min) < 1e-12
        fixed_idx = 1
    elseif abs(fixed_val - val_max) < 1e-12
        fixed_idx = nv[fixed_dir]
    else
        error("fixed_val=$fixed_val is neither min=$val_min nor max=$val_max")
    end

    face_cps = Int[]
    if fixed_dir == 3  # ζ fixed → face CPs indexed by (ξ, η)
        k = fixed_idx
        for j in 1:n2, i in 1:n1
            lin = (k-1)*n1*n2 + (j-1)*n1 + i
            push!(face_cps, Ppc[lin])
        end
    elseif fixed_dir == 1  # ξ fixed → face CPs indexed by (η, ζ)
        i = fixed_idx
        for k in 1:n3, j in 1:n2
            lin = (k-1)*n1*n2 + (j-1)*n1 + i
            push!(face_cps, Ppc[lin])
        end
    elseif fixed_dir == 2  # η fixed → face CPs indexed by (ξ, ζ)
        j = fixed_idx
        for k in 1:n3, i in 1:n1
            lin = (k-1)*n1*n2 + (j-1)*n1 + i
            push!(face_cps, Ppc[lin])
        end
    end

    return face_cps
end

# ─── Main export function ────────────────────────────────────────────────────

"""
    export_blender(prefix, npc, nsd, npd, p_mat, n_mat, KV, P, B;
                    faces=nothing, n_vis=6,
                    U=nothing, ID=nothing, E=nothing, nu=nothing,
                    scalar_fn=nothing, deformed=false)

Export IGA geometry for Blender rendering:

- `prefix_patch_k.obj`  — tessellated NURBS surface for each patch face
- `prefix_cpnet_k.obj`  — control net wireframe for each patch
- `prefix_cpts.obj`     — all control points as vertices
- `prefix_import.py`    — Blender Python script for one-click import + scene setup

**Arguments**:
- `faces`: Dict(patch_idx => [face_ids...]) specifying which faces to export.
  For 2D patches, use `0` for the full patch. Defaults: all outer faces.
- `scalar_fn`: `(x,y,z) -> Float64` — evaluated at each surface point
  and stored as vertex color for Blender's color attribute.
"""
function export_blender(
    prefix::String,
    npc::Int, nsd::Int, npd::Int,
    p_mat::Matrix{Int}, n_mat::Matrix{Int},
    KV, P::Vector{Vector{Int}}, B::Matrix{Float64};
    faces::Union{Nothing, Dict{Int, Vector{Int}}} = nothing,
    n_vis::Int = 6,
    U::Union{Nothing, Vector{Float64}} = nothing,
    ID::Union{Nothing, Matrix{Int}} = nothing,
    E::Union{Nothing, Float64} = nothing,
    nu::Union{Nothing, Float64} = nothing,
    scalar_fn::Union{Nothing, Function} = nothing,
    deformed::Bool = false
)
    # Default faces: for 3D export outer boundary faces, for 2D full patch
    if isnothing(faces)
        if npd == 2
            faces = Dict(pc => [0] for pc in 1:npc)
        else
            # Export all 6 faces of each patch by default
            faces = Dict(pc => [1,2,3,4,5,6] for pc in 1:npc)
        end
    end

    obj_files = String[]

    # ── Tessellated surfaces (one OBJ per patch, all faces merged) ──────
    for (pc, face_list) in sort(collect(faces))
        all_pts     = zeros(3, 0)
        all_normals = zeros(3, 0)
        all_svm     = Float64[]
        all_tris    = zeros(Int, 3, 0)
        vert_offset = 0

        for face in face_list
            pts, tris, normals, svm = tessellate_patch_surface(
                pc, face, nsd, npd, p_mat, n_mat, KV, P, B;
                n_vis=n_vis, U=U, ID=ID, E=E, nu=nu,
                scalar_fn=scalar_fn, deformed=deformed
            )
            all_pts     = hcat(all_pts, pts)
            all_normals = hcat(all_normals, normals)
            append!(all_svm, svm)
            all_tris    = hcat(all_tris, tris .+ vert_offset)
            vert_offset += size(pts, 2)
        end

        fname = "$(prefix)_patch_$(pc).obj"
        write_patch_obj(fname, all_pts, all_tris;
                        normals=all_normals,
                        scalars=(!isnothing(scalar_fn) ? all_svm : nothing))
        push!(obj_files, fname)
    end

    # ── Control net ───────────────────────────────────────────────────────
    for pc in 1:npc
        fname = "$(prefix)_cpnet_$(pc).obj"
        write_cpnet_obj(fname, B, P[pc], n_mat[pc, :])
        push!(obj_files, fname)
    end

    # ── All control points as a single point cloud ────────────────────────
    # Blender's OBJ importer doesn't support 'p' (point) elements.
    # Write vertices only — Geometry Nodes Mesh to Points handles loose verts.
    fname_cpts = "$(prefix)_cpts.obj"
    seen = Set{Int}()
    open(fname_cpts, "w") do f
        println(f, "# IGA control points — generated by export_blender.jl")
        for pc in 1:npc, A in P[pc]
            A in seen && continue
            push!(seen, A)
            @printf(f, "v %.8e %.8e %.8e\n", B[A,1], B[A,2], B[A,3])
        end
        # Degenerate edges so Blender imports the vertices as a mesh object
        for i in 1:length(seen)
            println(f, "l $i $i")
        end
    end
    push!(obj_files, fname_cpts)
    @printf("  Wrote %s  (%d control points)\n", fname_cpts, length(seen))

    # ── Blender Python import script ──────────────────────────────────────
    write_blender_script(prefix, obj_files)

    println("\n  Done. To render in Blender:")
    println("    1. Open Blender")
    println("    2. File → Import → Run Script: $(prefix)_import.py")
    println("    or from command line:  blender --python $(prefix)_import.py")
end

# ─── Blender Python import + scene setup script ─────────────────────────────

function write_blender_script(prefix::String, obj_files::Vector{String})
    fname = "$(prefix)_import.py"
    open(fname, "w") do f
        write(f, """
# $(prefix)_import.py — Auto-generated Blender import script
# Run: blender --python $(prefix)_import.py
# Or:  File > Scripting > Open > Run Script

import bpy
import os
import math
from pathlib import Path

# ─── Clean default scene ──────────────────────────────────────────────
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

# Delete default collection objects
for obj in bpy.data.objects:
    bpy.data.objects.remove(obj, do_unlink=True)

script_dir = str(Path(bpy.data.filepath).parent) if bpy.data.filepath else os.getcwd()

# ─── Materials ────────────────────────────────────────────────────────

def make_surface_material(name="IGA_Surface", color=(0.15, 0.35, 0.65, 1.0)):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Metallic"].default_value = 0.1
    bsdf.inputs["Roughness"].default_value = 0.4
    bsdf.inputs["Specular IOR Level"].default_value = 0.5
    return mat

def make_vertex_color_material(name="IGA_Scalar"):
    \"\"\"Material that reads vertex colors (from OBJ 'v x y z r g b').\"\"\"
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    tree = mat.node_tree
    bsdf = tree.nodes["Principled BSDF"]
    bsdf.inputs["Metallic"].default_value = 0.05
    bsdf.inputs["Roughness"].default_value = 0.35
    bsdf.inputs["Specular IOR Level"].default_value = 0.5
    # Color Attribute node → Base Color (layer name set at import time)
    ca = tree.nodes.new('ShaderNodeVertexColor')
    ca.location = (-300, 300)
    ca.layer_name = ""  # will be set after import
    tree.links.new(ca.outputs['Color'], bsdf.inputs['Base Color'])
    return mat

def make_wireframe_material(name="CP_Net", color=(0.9, 0.3, 0.1, 1.0)):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Metallic"].default_value = 0.0
    bsdf.inputs["Roughness"].default_value = 0.8
    return mat

def make_cp_material(name="CP_Points", color=(0.85, 0.08, 0.08, 1.0)):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Metallic"].default_value = 0.6
    bsdf.inputs["Roughness"].default_value = 0.3
    return mat

mat_surface = make_surface_material()
mat_scalar  = make_vertex_color_material()
mat_cpnet   = make_wireframe_material()
mat_cp      = make_cp_material()

# ─── Import OBJ files ────────────────────────────────────────────────

def import_obj(filepath, collection_name):
    \"\"\"Import OBJ and move to named collection.\"\"\"
    if not os.path.isabs(filepath):
        filepath = os.path.join(script_dir, filepath)
    if not os.path.exists(filepath):
        print(f"  SKIP (not found): {filepath}")
        return None

    # Create collection if needed
    if collection_name not in bpy.data.collections:
        col = bpy.data.collections.new(collection_name)
        bpy.context.scene.collection.children.link(col)
    col = bpy.data.collections[collection_name]

    before = set(bpy.data.objects.keys())
    bpy.ops.wm.obj_import(filepath=filepath)
    after = set(bpy.data.objects.keys())
    new_objs = after - before

    for name in new_objs:
        obj = bpy.data.objects[name]
        # Move to our collection
        for c in obj.users_collection:
            c.objects.unlink(obj)
        col.objects.link(obj)

    return [bpy.data.objects[n] for n in new_objs]

# Import patch surfaces
patch_files = [f for f in $(repr(obj_files)) if "_patch_" in f]
for pf in patch_files:
    objs = import_obj(pf, "Patches")
    if objs:
        for obj in objs:
            obj.data.materials.clear()
            # Use vertex-color material if the mesh has color attributes
            if obj.data.color_attributes:
                layer_name = obj.data.color_attributes[0].name
                mat_vc = make_vertex_color_material(name=f"IGA_Scalar_{obj.name}")
                # Set the layer name to match what the OBJ importer created
                for node in mat_vc.node_tree.nodes:
                    if node.type == 'VERTEX_COLOR':
                        node.layer_name = layer_name
                obj.data.materials.append(mat_vc)
            else:
                obj.data.materials.append(mat_surface)
            # Smooth shading
            for poly in obj.data.polygons:
                poly.use_smooth = True

# Import control nets
cpnet_files = [f for f in $(repr(obj_files)) if "_cpnet_" in f]
for cf in cpnet_files:
    objs = import_obj(cf, "ControlNet")
    if objs:
        for obj in objs:
            # Convert edges to renderable tubes via Geometry Nodes
            # (Wireframe modifier doesn't work on OBJ line elements)
            gn_mod = obj.modifiers.new(name="EdgeTubes", type='NODES')
            tree = bpy.data.node_groups.new("CP_Net_Tubes", 'GeometryNodeTree')
            tree.interface.new_socket('Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
            tree.interface.new_socket('Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')

            inp = tree.nodes.new('NodeGroupInput')
            inp.location = (-400, 0)
            out = tree.nodes.new('NodeGroupOutput')
            out.location = (400, 0)

            # Mesh to Curve → Curve to Mesh with circle profile → Set Material
            m2c = tree.nodes.new('GeometryNodeMeshToCurve')
            m2c.location = (-300, 0)

            circle = tree.nodes.new('GeometryNodeCurvePrimitiveCircle')
            circle.location = (-300, -200)
            circle.inputs['Resolution'].default_value = 8
            circle.inputs['Radius'].default_value = 0.006

            c2m = tree.nodes.new('GeometryNodeCurveToMesh')
            c2m.location = (-100, 0)

            setmat = tree.nodes.new('GeometryNodeSetMaterial')
            setmat.location = (100, 0)
            setmat.inputs['Material'].default_value = mat_cpnet

            tree.links.new(inp.outputs[0], m2c.inputs['Mesh'])
            tree.links.new(m2c.outputs['Curve'], c2m.inputs['Curve'])
            tree.links.new(circle.outputs['Curve'], c2m.inputs['Profile Curve'])
            tree.links.new(c2m.outputs['Mesh'], setmat.inputs['Geometry'])
            tree.links.new(setmat.outputs['Geometry'], out.inputs[0])

            gn_mod.node_group = tree
            obj.data.materials.clear()
            obj.data.materials.append(mat_cpnet)

# Import control points
cpts_file = [f for f in $(repr(obj_files)) if "_cpts" in f]
for cf in cpts_file:
    objs = import_obj(cf, "ControlPoints")
    if objs:
        for obj in objs:
            # Convert vertices to spheres via geometry nodes
            gn_mod = obj.modifiers.new(name="PointSpheres", type='NODES')
            # Create a simple geometry node tree: Mesh to Points → Instance on Points
            tree = bpy.data.node_groups.new("CP_Spheres", 'GeometryNodeTree')
            tree.interface.new_socket('Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
            tree.interface.new_socket('Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')

            inp = tree.nodes.new('NodeGroupInput')
            inp.location = (-400, 0)
            out = tree.nodes.new('NodeGroupOutput')
            out.location = (400, 0)

            m2p = tree.nodes.new('GeometryNodeMeshToPoints')
            m2p.location = (-300, 0)
            m2p.inputs['Radius'].default_value = 0.015

            iop = tree.nodes.new('GeometryNodeInstanceOnPoints')
            iop.location = (-100, 0)

            sphere = tree.nodes.new('GeometryNodeMeshIcoSphere')
            sphere.location = (-300, -200)
            sphere.inputs['Radius'].default_value = 0.015
            sphere.inputs['Subdivisions'].default_value = 3

            setmat = tree.nodes.new('GeometryNodeSetMaterial')
            setmat.location = (100, 0)
            setmat.inputs['Material'].default_value = mat_cp

            tree.links.new(inp.outputs[0], m2p.inputs['Mesh'])
            tree.links.new(m2p.outputs['Points'], iop.inputs['Points'])
            tree.links.new(sphere.outputs['Mesh'], iop.inputs['Instance'])
            tree.links.new(iop.outputs['Instances'], setmat.inputs['Geometry'])
            tree.links.new(setmat.outputs['Geometry'], out.inputs[0])

            gn_mod.node_group = tree
            obj.data.materials.clear()
            obj.data.materials.append(mat_cp)

# ─── Shadow-catcher ground plane ─────────────────────────────────────
# White studio floor that catches shadows but is otherwise invisible.

bpy.ops.mesh.primitive_plane_add(size=20, location=(0, 0, -0.01))
ground = bpy.context.active_object
ground.name = "ShadowCatcher"
ground.is_shadow_catcher = True
# White diffuse material (only visible via shadows)
mat_ground = bpy.data.materials.new(name="Ground")
mat_ground.use_nodes = True
bsdf_g = mat_ground.node_tree.nodes["Principled BSDF"]
bsdf_g.inputs["Base Color"].default_value = (1.0, 1.0, 1.0, 1.0)
bsdf_g.inputs["Roughness"].default_value = 1.0
ground.data.materials.append(mat_ground)

# ─── Lighting (3-point studio setup) ─────────────────────────────────

# Key light — main shadow caster
key = bpy.data.lights.new(name="Key", type='AREA')
key.energy = 300
key.size = 4.0
key.color = (1.0, 0.98, 0.95)
key_obj = bpy.data.objects.new("Key", key)
bpy.context.scene.collection.objects.link(key_obj)
key_obj.location = (4.0, -3.0, 5.0)
key_obj.rotation_euler = (math.radians(45), 0, math.radians(30))

# Fill light
fill = bpy.data.lights.new(name="Fill", type='AREA')
fill.energy = 100
fill.size = 5.0
fill.color = (0.85, 0.9, 1.0)
fill_obj = bpy.data.objects.new("Fill", fill)
bpy.context.scene.collection.objects.link(fill_obj)
fill_obj.location = (-4.0, -2.0, 3.5)
fill_obj.rotation_euler = (math.radians(60), 0, math.radians(-45))

# Rim / back light
rim = bpy.data.lights.new(name="Rim", type='SPOT')
rim.energy = 200
rim.spot_size = math.radians(60)
rim.color = (1.0, 0.95, 0.9)
rim_obj = bpy.data.objects.new("Rim", rim)
bpy.context.scene.collection.objects.link(rim_obj)
rim_obj.location = (1.0, 4.0, 4.0)
rim_obj.rotation_euler = (math.radians(-150), 0, math.radians(10))

# ─── Camera with depth of field ──────────────────────────────────────

import mathutils

cam = bpy.data.cameras.new("Camera")
cam.lens = 85           # portrait lens — nice DoF compression
cam.dof.use_dof = True
cam.dof.aperture_fstop = 4.0   # moderate depth of field
cam_obj = bpy.data.objects.new("Camera", cam)
bpy.context.scene.collection.objects.link(cam_obj)
cam_obj.location = (5.0, -5.0, 4.0)   # pulled back for full view

# Point camera at origin
direction = mathutils.Vector((0, 0, 0.3)) - cam_obj.location
rot_quat = direction.to_track_quat('-Z', 'Y')
cam_obj.rotation_euler = rot_quat.to_euler()

# Focus on origin
cam.dof.focus_distance = direction.length

bpy.context.scene.camera = cam_obj

# ─── Render settings ─────────────────────────────────────────────────

scene = bpy.context.scene
scene.render.engine = 'CYCLES'
scene.cycles.samples = 256
scene.cycles.use_denoising = True
scene.render.resolution_x = 2400
scene.render.resolution_y = 1800
scene.render.film_transparent = False   # white background with shadows

# ─── World (studio white) ────────────────────────────────────────────
world = bpy.data.worlds.new("StudioWhite")
world.use_nodes = True
bg = world.node_tree.nodes["Background"]
bg.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
bg.inputs["Strength"].default_value = 1.0
scene.world = world

print("\\n✓ Scene ready. Adjust camera, then Render → Render Image (F12).")
print("  Collections: Patches, ControlNet, ControlPoints")
print("  Toggle visibility per collection in the Outliner.")
print("  Ground plane casts shadows on white background.")
""")
    end
    @printf("  Wrote %s  (Blender import script)\n", fname)
end
